### ISSUE TITLE
not playing after upgrade to Firefox 44.0

### ISSUE THREAD

**Issue by jikard0** [flowplayer/flowplayer-hlsjs#20] opened 2016-01-28 19:21 UTC
Double picture or nor playing hls at all on Firefox 44.0(Windows)

**Comment by jikard0** [comment] 2016-01-29 09:32
My apologies for double issue(flowplayer and flowplayer-hlsjs). The reason was i cannot decided where the problem is located. Now I'm sure it is located in flowplayer-hlsjs plug-in or in hls.js(dailymotion).
With flash fall-back(flashls) everything seems to be fine. More information from my side.
This happen only with FF 44 on Windows 7,8,8.1,10. Below that version of FF for example 43.1 hlsjs engine runs well. Also on other browsers IE,EDGE,CHROME,Safari works well.
Stream source is Wowza(latest release). 
Flowplayer is 6.0.5 open source(from github including latest commit from Jan 13, 2016)
Flowplayer hlsjs is from github  include latest commit( hls.js: upgrade to v0.4.7). Even more i upgrade hls.js from latest dev version(latest commit at 29.Jan.2016).
flowplayer and flowplayer-hlsjs versions not minified.

Below is link where you can test
http://www.kitaiskitelefoni.net/flowplayer/

**Comment by blacktrash** [comment] 2016-01-29 12:20
Please test the stream in the hls.js sample player: http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2F176.31.50.48%3A1935%2Ftest%2F2014tvtvp1%2Fplaylist.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&levelCapping=-1 to find out whether it's a problem with the plugin or the hls.js client.
If the problem can be observed with the above, then you should take this to the hls.js bug tracker first: https://github.com/dailymotion/hls.js/issues

**Comment by blacktrash** [comment] 2016-01-29 15:54
@jikard0 - monitoring https://github.com/dailymotion/hls.js/issues/217 - thanks.

**Comment by jikard0** [comment] 2016-01-29 16:16
I will.
Thank you

On 29 January 2016 at 17:54, Christian Ebert <notifications@github.com>
wrote:

> @jikard0 <https://github.com/jikard0> - monitoring dailymotion/hls.js#217
> <https://github.com/dailymotion/hls.js/issues/217> - thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flowplayer/flowplayer-hlsjs/issues/20#issuecomment-176832810>
> .
>



-- 
Best regards
Jivko Todorov
jivkohtodorov@gmail.com
+359885511038

**Comment by blacktrash** [comment] 2016-01-29 22:49
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1244294 - Firefox regression on Windows, fixed in FF45, will not be fixed in FF44.

**Comment by jikard0** [comment] 2016-01-30 14:36
Seems should wait for next FF release

**Comment by blacktrash** [comment] 2016-01-30 14:47
@jikard0 - yes, too late for 44 beta.

**Comment by nnarhinen** [comment] 2016-01-30 18:51
@blacktrash as 44 will be around a while (until march at least), is there any way we could not register this plugin for FF44 and make it correctly fallback to flashls?

**Comment by blacktrash** [comment] 2016-01-30 19:13
@nnarhinen - sure. Already looking into it.
@bbbo - can you confirm that this happens for other streams too? According to your answer here https://github.com/flowplayer/flowplayer/issues/991#issuecomment-176358961 this is not the case?

**Comment by blacktrash** [comment] 2016-01-30 19:18
I wonder whether this is caused by a sample aspect ratio != 1/1 in the stream.
If this does not apply to all streams I will probably make this an option for FF44 on Win.

**Comment by bbbo** [comment] 2016-01-31 16:15
indeed, http://demos.flowplayer.org/api/hlsjs.html plays fine for me in FF44 (Win7), and so does http://stylebites.de/fp6/maxcdn.html for example

**Comment by blacktrash** [comment] 2016-01-31 19:41
The problem with adding the option is that one then 'fails over' to flash hls which cannot handle anamorphic video either because Flash is agnostic of display aspect ratio. See our encoding docs.
That is http://176.31.50.48:1935/test/2014tvtvp1/playlist.m3u8 will be played distorted at 4:3 aspect ratio.
So the configuration would be:
```js
clip: {
  hlsjs: {
    anamorphic: true
  },
  sources: [
    { type: "application/x-mpegurl", src: "myplaylist.m3u8", engine: "hlsjs" },
    { type: "application/x-mpegurl", src: "myplaylist.m3u8", engine: "html5" },
    // non-hls sources here
  ]
}
```
@jikard0 - for live streams this means that it will simply not be played on Firefox 44 Windows - or you don't mind that it's viewed in 4:3 aspect ratio.

**Comment by blacktrash** [comment] 2016-02-01 20:42
Not 100% sure about this `anamorphic` option, because it basically passes the problem on to flash hls (albeit with a different symptom).
Basically one is bound to run into problems with anamorphic video at least from time to time, see: https://flowplayer.org/docs/encoding.html - it's a tempting way save bandwidth, but risks pitfalls with oscillating quality of browser decoder implementations.
Closing this for now.

**Closed by blacktrash** 2016-02-01 20:42 UTC
