### ISSUE TITLE
HLS error in loading source causing player crashes

### ISSUE THREAD

**Issue by RyanQuackenbush** [flowplayer/flowplayer-hlsjs#32] opened 2016-05-20 01:37 UTC
If I attempt to load an HLS source and the source can not load (e.g. the default "hlsjs: Video file not found" shows as the background), I'm not able to player.unload the player back to the splash screen. 

Unload works fine with sources which load fine. I'm assuming most actions won't work after the error since the execution context has thrown an error at this point, but I've only tested unload personally.

I get an error: 
```
flowplayer.hlsjs.min.js:22 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
```

Browser: Chrome 50 / Firefox 46

**Comment by blacktrash** [comment] 2016-05-20 05:21
We would need more details. Please provide a link to a *minimal* sample page demonstrating the problem.
Are you using the latest version of the plugin?
Does it happen for you here http://demos.flowplayer.org/api/live-check.html as well? 2 example scenarios similar to yours if I understand correctly - for me it doesn't.
Does it happen in all browsers?

**Comment by RyanQuackenbush** [comment] 2016-05-20 15:05
Thanks for the reply. I've created a simple fiddle:

[jsFiddle](https://jsfiddle.net/Riffic/03gvk1er/)

Scenario 1:
- Click load video
- Plays video w/o issue
- Click load video again
- Reloads video and plays video w/o issue

Scenario 2:
- Click splash screen 
- Loads failed video
- Click load video
- Video fails to load and play

**Comment by RyanQuackenbush** [comment] 2016-05-20 17:07
Leaving this here for any future HLS problems others might have:

Essentially what ended up working was following the http://demos.flowplayer.org/api/live-check.html demo to some degree. It seems errors in HLS can be fatal or none fatal.

( Available [HLS Errors](https://github.com/dailymotion/hls.js/blob/v0.5.30/src/events.js) )

```js
player.on('hlsError', function ( e, api, data ){
    if( data.fatal ){
        //recover here, maybe check data.details for type of error
        //possibly api.trigger("error", [ api, {code: 4, video: videoInfo}] );
    }
});
```

Removing the "is-error" class on the player element seems to reset the player to the splash screen where you can then load another video via the ```api.load``` load method if desired.

Essentially @blacktrash this is where I feel it's a bug. Having to remove "is-error" seems wrong to me if ```api.load``` is called (and it still throws the DOMException error behind the scenes). Either way I have a work around which is sufficient.

**Comment by RyanQuackenbush** [comment] 2016-05-20 17:15
As a recommended fix the player should set the player ```error``` and ```loading``` properties to false and remove ```is-error``` element class when a ```api.load``` call is made by default, but maybe there is  a reason it doesn't do this automatically?

**Comment by blacktrash** [comment] 2016-05-20 22:11
@RyanQuackenbush - the error state is considered a 'special' state, usually you should avoid it, therefore this is the 'canonical' way of recovery: http://demos.flowplayer.org/scripting/recover.html
Recovery should be a last resort, and should arguably not be made easy. But you can use the API to recover with relative ease, if you know what you're doing and why. - Also consider that this may interfere with other scenarios where one relies on the loading state _not_ to be overridden when calling `load()`.
Feel free to argue your case in the core player issue tracker.

**Comment by blacktrash** [comment] 2016-07-04 09:58
No feedback. Closing.

**Closed by blacktrash** 2016-07-04 09:58 UTC

**Comment by frutality** [comment] 2016-08-09 10:47
Seems like hls.js bug, or Chrome maybe.

But it also seems like they fixed it (https://github.com/dailymotion/hls.js/issues/388). And I'm not sure why I'm seeing this too.

Here's my setup: http://pastebin.com/6V7vydvm
Streaming with OBS (x264, max bitrate 1000 kb/s / AAC)
Streaming to nginx-rtmp-module.

HLS Stream works well in Firefox, IE, Edge and iOS Safari. 
Haven't any Android device to try.
Not working in Chrome on Windows 10:

> hlsjs: Video file not found
> http://192.168.1.35:8080/hls/obs/index.m3u8

Here screenshots of Network tab: http://imgur.com/a/1N5N3

Can't reproduce bug with flowplayer demos, and that's why I'm confused. Any thoughts?

**Comment by blacktrash** [comment] 2016-08-09 11:39
@frutality - as you're delivering with `Cache-Control: no-cache` headers, this may be the cause: https://github.com/dailymotion/hls.js/issues/615#issuecomment-238424466

**Comment by frutality** [comment] 2016-08-09 13:04
Well.. this is probably webserver issue, but I'm not sure. I turned off `Cache-Control: no-cache` and no difference. If I click `F5` to refresh page — there is `hlsjs: Video file not found` error. But if I hit `F6` and then `Enter` — stream is playing.

But not in FF. My FF stream seems broken now. I'll try investigate into cache-like things.

**Comment by frutality** [comment] 2016-08-09 15:38
Seems like false alarm. 

I tried to watch stream at another PC in my LAN — it works perfectly. So I think I had an issue with network or vagrant or something related. Stream is buggy when I try to watch it on PC, from where I publish stream and run Vagrant with webserver.

So, default config (`add_header Cache-Control no-cache;`) works fine. Well, truth is that FF stopped video after ~5 min playing, but that's another issue I think.
