### ISSUE TITLE
Cannot read property 'AUDIO' of undefined

### ISSUE THREAD

**Issue by piuccio** [flowplayer/flowplayer-hlsjs#73] opened 2017-05-24 02:30 UTC
[this line](https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L158) now throws an exception because `attrs` is undefined in the video I'm trying to play.

```
flowplayer.hlsjs.js:158 Uncaught TypeError: Cannot read property 'AUDIO' of undefined
    at eval (webpack:///./~/flowplayer-hlsjs/flowplayer.hlsjs.js?:158:53)
    at Array.forEach (native)
    at initAudio (webpack:///./~/flowplayer-hlsjs/flowplayer.hlsjs.js?:157:37)
    at EventEmitter.eval (webpack:///./~/flowplayer-hlsjs/flowplayer.hlsjs.js?:784:41)
    at EventEmitter.emit (webpack:///./~/hls.js/dist/hls.js?:97:20)
    at EventEmitter.trigger (webpack:///./~/hls.js/dist/hls.js?:10217:21)
    at PlaylistLoader.loadsuccess (webpack:///./~/hls.js/dist/hls.js?:11416:17)
    at XhrLoader.readystatechange (webpack:///./~/hls.js/dist/hls.js?:15800:28)
```

**Comment by piuccio** [comment] 2017-05-24 04:28
marginally related, it would be much better if you could publish this plugin to npm so users can adopt semver instead of always pulling from master

**Comment by blacktrash** [comment] 2017-05-24 12:23
@piuccio - thanks for bringing this up, should be fixed now.

Regarding your hints at deployment improvements: I do not like the 'selfupdating' procedure myself, however:
- you can obtain a (kind of) 'stable' release from https://github.com/flowplayer/flowplayer-hlsjs/releases
- I dislike the 'selfupdating' deployment style a lot, but still do not see a way around it because arguably the vast majority of users would not keep up with the fast moving hls.js client lib and/or emergency fixes because of (selfupdating) browser whims[1]
- with webpack there is this corner case: #43 - no-one has got to the bottom of it so far; hard to repro, but last time I checked it still happened; that's why the 'canonical' plugin is not built that way
- nevermind that this is/was a bug, I would be interested in a stream example where this happened

[1] This puts the strain of testing etc. on us, with the risk of errors on entirely on our side. While we are doing quite well overall, for those who want to share the burden there is this pragmatic approach:
- use a release or version which works with your streams etc.
- check from time to time yourself whether the latest works
- if yes: upgrade to latest
- repeat cycle

Then you are master and in charge of the timing.

**Comment by piuccio** [comment] 2017-05-24 13:15
Your concern are valid and that's exactly why most people have adopted semver and npm range. 
By default when you use nom install - - save you'll get something like ^1.0.0 meaning you'll automatically get all updates in version 1.
You'll be free to do what you want with the master branch knowing that you won't break other websites. 

Anyway I've locked down the version but I'm loosing the ability to use automatic tools to remind me of dependency updates, not a big deal

**Comment by blacktrash** [comment] 2017-05-24 13:46
- the vast majority of our users do not deploy via NPM
- of course, as you found out, I cannot guarantee that we won't break websites with the 'selfupdate' approach; but I am reluctantly forced to do it that way, not least because browser developers use it, and can't guarantee anything either, as we found out multiple times ;-)

Could you confirm that the issue is fixed for you?

**Closed** 2017-06-10 23:42 UTC
